# Generated by Django 3.0.9 on 2020-08-06 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('fname', models.CharField(max_length=15, verbose_name='First name')),
                ('minit', models.CharField(max_length=1, verbose_name='Initial second name', null=False)),
                ('lname', models.CharField(max_length=15, verbose_name='Last name')),
                ('ssn', models.CharField(max_length=9, primary_key=True, serialize=False, verbose_name='Ssn')),
                ('bdate', models.DateTimeField(verbose_name='Birth date')),
                ('address', models.CharField(max_length=100, verbose_name='Address')),
                ('sex', models.CharField(max_length=1, verbose_name='Sex')),
                ('salary', models.FloatField(verbose_name='Salary')),
                ('dno', models.IntegerField(verbose_name='Dno')),
            ],
        ),
    ]
